const $ = id => document.getElementById(id);
const valueOf = id => { const el = $(id); return el ? String(el.value ?? '').trim() : ''; };
const esc = value => String(value ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let me = null;

function openLogin(role){ showPage('loginPage'); const r=$('loginRole'); if(r){r.value=role; updateLoginFields();} }
function openRegistration(){ openLogin('staff'); }
function openEmergency(){ showPage('emergencyPage'); }
function scrollToSection(id){ $(id)?.scrollIntoView({behavior:'smooth'}); }
function toggleMenu(){ $('mobileMenu')?.classList.toggle('active'); }
function showPage(id){ ['homePage','loginPage','emergencyPage','dashboard'].forEach(x=>$(x)?.classList.remove('active')); $(id)?.classList.add('active'); window.scrollTo({top:0,behavior:'smooth'}); }
function goHome(){ showPage('homePage'); }
function notice(id,text,good=false){ if($(id)) $(id).innerHTML=`<div class="notice ${good?'success':'error'}">${esc(text)}</div>`; }
function closeModal(){ $('modal')?.classList.remove('active'); document.body.classList.remove('modal-open'); }
function openModal(html){ const m=$('modal'), c=$('modalContent'); if(!m||!c){alert('Panel unavailable. Please refresh.');return;} c.innerHTML=html; m.classList.add('active'); document.body.classList.add('modal-open'); }

async function api(path, options={}){
  const response=await fetch(path,{credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  const data=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(data.error||'Request failed.');
  return data;
}

function updateLoginFields(){
  const role=valueOf('loginRole');
  const label=$('loginIdentifierLabel'); const input=$('loginIdentifier'); const wrap=$('patientCardTypeWrap'); const pw=$('loginPasswordWrap');
  if(!label||!input) return;
  const patient=role==='patient';
  label.childNodes[0].textContent=patient?'Card Number':'Email';
  input.type=patient?'text':'email';
  input.placeholder=patient?'Enter Card Number':'Enter clinic email';
  if(wrap) wrap.classList.toggle('hidden',!patient);
  if(pw) pw.classList.toggle('hidden',patient);
}
async function login(){
  try{
    const role=valueOf('loginRole'), identifier=valueOf('loginIdentifier');
    const cardType=valueOf('loginCardType');
    if(!role||!identifier) throw new Error('Please enter your card number.');
    if(role==='patient'){
      if(!['Personal','Family'].includes(cardType)) throw new Error('Please choose Personal or Family Card.');
    } else {
      const password=valueOf('loginPassword');
      if(!password) throw new Error('Please enter your password.');
    }
    const body={role,identifier,cardType};
    if(role!=='patient') body.password=valueOf('loginPassword');
    const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(body)});
    me=d.user; await loadDashboard();
  }catch(e){notice('loginMessage',e.message);}
}

function setBaseDashboard(){
  showPage('dashboard'); $('logoutBtn')?.classList.remove('hidden');
  ['patientDashboard','staffDashboard','doctorDashboard','adminDashboard'].forEach(id=>$(id)?.classList.add('hidden'));
  $('welcome').textContent=`Welcome, ${me.firstName} ${me.lastName}`;
  let identity='';
  if(me.role==='patient') identity=`Card Number: ${me.cardNumber||me.patientId||''} • ${me.cardType||'Personal'}${me.familyCardNumber?` • Family Card: ${me.familyCardNumber}`:''}${me.cardName?` • ${me.cardName}`:''}`;
  if(me.role==='staff') identity=`Staff ID: ${me.staffId}`;
  if(me.role==='doctor') identity=`Doctor ID: ${me.doctorId}`;
  if(me.role==='admin') identity=`Administrator ID: ${me.adminId}`;
  $('identity').innerHTML=`<span class="badge">${esc(me.role.toUpperCase())}</span> &nbsp; ${esc(identity)}`;
}
async function loadDashboard(){setBaseDashboard(); if(me.role==='patient')return loadPatient(); if(me.role==='staff')return loadStaff(); if(me.role==='doctor')return loadDoctor(); return loadAdmin();}

function patientShell(){return `<div class="stats"><div class="stat"><strong id="patientAppointments">0</strong>Appointments</div><div class="stat"><strong id="patientPrescriptions">0</strong>Prescriptions</div><div class="stat"><strong id="patientPayments">0</strong>Payments</div><div class="stat"><strong id="patientVitals">0</strong>Vitals</div></div><div class="dashboard-card"><h2>My Card</h2><div class="demo"><b>Card Number:</b> <span id="myCardNumber"></span><br><b>Card Type:</b> <span id="myCardType"></span><br><b>Card Name:</b> <span id="myCardName"></span><br><span id="myFamilyCard"></span></div></div><div class="dash-grid" style="margin-top:18px"><div class="dashboard-card"><h2>Book an Appointment</h2><label>Date<input id="aptDate" type="datetime-local"></label><label>Type<select id="aptType"><option>Consultation</option><option>Follow-up</option><option>Operation</option><option>Laboratory</option></select></label><label>Reason<textarea id="aptReason"></textarea></label><button class="primary" onclick="bookAppointment()">Book Appointment</button></div><div class="dashboard-card"><h2>My Appointments</h2><div id="patientAppointmentList"></div></div></div><div class="dashboard-card" style="margin-top:18px"><h2>My Medical History</h2><div class="dash-grid"><div><h3>Prescriptions</h3><div id="patientPrescriptionList"></div></div><div><h3>Payments</h3><div id="patientPaymentList"></div><h3>Vitals</h3><div id="patientVitalsList"></div></div></div></div><div class="dashboard-card" style="margin-top:18px"><h2>Family Card</h2><div id="familyMembers"></div></div>`;}
async function loadPatient(){
  const area=$('patientDashboard'); area.classList.remove('hidden'); area.innerHTML=patientShell(); const d=await api('/api/patient/dashboard');
  $('patientAppointments').textContent=d.appointments.length; $('patientPrescriptions').textContent=d.prescriptions.length; $('patientPayments').textContent=d.payments.length; $('patientVitals').textContent=d.vitals.length;
  $('myCardNumber').textContent=d.cardNumber||d.patientId||''; $('myCardType').textContent=d.cardType||''; $('myCardName').textContent=d.cardName||''; $('myFamilyCard').textContent=d.familyCardNumber?`Family Card Number: ${d.familyCardNumber}`:'';
  $('patientAppointmentList').innerHTML=d.appointments.length?d.appointments.map(a=>`<div class="item"><h4>${esc(a.type)}</h4>${esc(a.date)}<br><span class="badge">${esc(a.status)}</span><p>${esc(a.reason)}</p></div>`).join(''):'<p class="identity">No appointments yet.</p>';
  $('patientPrescriptionList').innerHTML=d.prescriptions.length?d.prescriptions.map(p=>`<div class="item"><b>${esc(p.drugName)}</b><br>${esc(p.dosage)} • ${esc(p.frequency)}<br>${esc(p.duration||'')}<br>${esc(p.instructions||'')}<br><span class="identity">Prescribed by ${esc(p.doctorName||'Doctor')}</span></div>`).join(''):'<p class="identity">No prescriptions.</p>';
  $('patientPaymentList').innerHTML=d.payments.length?d.payments.map(p=>`<div class="item"><b>₦${esc(p.amount)}</b> — ${esc(p.service)}<br><span class="badge">${esc(p.method)}</span> ${esc(p.status)}</div>`).join(''):'<p class="identity">No payments.</p>';
  $('patientVitalsList').innerHTML=d.vitals.length?d.vitals.map(v=>`<div class="item">BP ${esc(v.bloodPressure)} • Pulse ${esc(v.pulse)} • Temp ${esc(v.temperature)}<br>SpO₂ ${esc(v.spo2||'')}<br><span class="identity">Recorded by ${esc(v.recordedByName||'Staff')} — Staff ID: ${esc(v.recordedByStaffId||'N/A')}</span></div>`).join(''):'<p class="identity">No vitals.</p>';
  $('familyMembers').innerHTML=d.familyMembers?.length?d.familyMembers.map(m=>`<div class="item"><b>${esc(m.firstName)} ${esc(m.lastName)}</b><br>${esc(m.cardType)} Card • ${esc(m.cardNumber||m.patientId||'')}<br>${esc(m.cardName||'')}</div>`).join(''):'<p class="identity">No family members linked to this card.</p>';
}
async function bookAppointment(){try{await api('/api/appointments',{method:'POST',body:JSON.stringify({date:valueOf('aptDate'),type:valueOf('aptType'),reason:valueOf('aptReason')})});alert('Appointment booked successfully.');await loadPatient();}catch(e){alert(e.message);}}

function staffShell(){return `<div class="tabs"><button class="active" onclick="staffTab('patients',this)">Patients</button><button onclick="staffTab('lookup',this)">Find by Card</button><button onclick="staffTab('register',this)">Register Patient</button><button onclick="staffTab('vitals',this)">Record Vitals</button><button onclick="staffTab('payments',this)">Payment</button><button onclick="staffTab('emergencies',this)">Emergencies</button></div><div id="staffPatientsTab" class="dashboard-card"></div><div id="staffLookupTab" class="dashboard-card hidden"></div><div id="staffRegisterTab" class="dashboard-card hidden"></div><div id="staffVitalsTab" class="dashboard-card hidden"></div><div id="staffPaymentsTab" class="dashboard-card hidden"></div><div id="staffEmergenciesTab" class="dashboard-card hidden"></div>`;}
async function loadStaff(){const area=$('staffDashboard');area.classList.remove('hidden');area.innerHTML=staffShell();await refreshStaff();}
async function refreshStaff(){
  const d=await api('/api/staff/queue');
  $('staffPatientsTab').innerHTML=`<h2>Patient Records</h2>${d.patients.length?d.patients.map(p=>`<div class="record"><div class="toolbar"><div><h3 style="margin:0">${esc(p.firstName)} ${esc(p.lastName)}</h3><span class="badge">${esc(p.cardType)} Card</span> <span class="badge">${esc(p.cardNumber||p.patientId||'')}</span><br><span class="identity">${esc(p.cardName||'')}</span></div><button class="outline" onclick="staffPatientDetails('${p.id}')">Open Patient Page</button></div></div>`).join(''):'<p class="identity">No patients registered.</p>'}`;
  $('staffLookupTab').innerHTML=`<h2>Confirm Patient by Card</h2><p class="identity">Staff must enter the Card Number and Card Type before accessing the patient page. A Family Card can contain multiple separate patient records.</p><div id="lookupMessage"></div><div class="form-grid"><label>Card Number<input id="lookupCardNumber"></label><label>Card Type<select id="lookupCardType"><option>Personal</option><option>Family</option></select></label></div><button class="primary" onclick="lookupPatient()">Confirm Card & Open Patient</button><div id="lookupResults" style="margin-top:18px"></div>`;
  $('staffRegisterTab').innerHTML=`<h2>Register Patient</h2><p class="identity">Only authorized staff register patients. Choose exactly one card type. The patient does not need a Gmail address.</p><div id="staffRegisterMessage"></div><div class="form-grid"><label>Patient First Name<input id="sFirst"></label><label>Patient Last Name<input id="sLast"></label><label>Card Type<select id="sCardType"><option>Personal</option><option>Family</option></select></label><label>Card Number<input id="sCardNumber" placeholder="Enter clinic card number"></label><label class="full">Card Name<input id="sCardName" placeholder="Personal card name or Family card name"></label><label>Phone<input id="sPhone"></label><label>Date of Birth<input id="sDob" type="date"></label><label>Sex<select id="sSex"><option>Male</option><option>Female</option></select></label><label class="full">Emergency Contact<textarea id="sEmergency"></textarea></label></div><button class="primary" onclick="staffRegister()">Create Patient Record</button>`;
  const opts=d.patients.map(p=>`<option value="${esc(p.id)}">${esc(p.firstName)} ${esc(p.lastName)} — ${esc(p.cardType)} — ${esc(p.cardNumber||p.patientId||'')}</option>`).join('');
  $('staffVitalsTab').innerHTML=`<h2>Record Patient Vitals</h2><p class="identity">Confirm the patient first, then record information against that patient's individual record.</p><div class="form-grid"><label class="full">Confirmed Patient<select id="vPatient">${opts||'<option value="">No patients registered</option>'}</select></label><label>Temperature<input id="vTemp"></label><label>Blood Pressure<input id="vBP"></label><label>Pulse<input id="vPulse"></label><label>Respiratory Rate<input id="vResp"></label><label>SpO₂<input id="vSpo"></label><label>Weight<input id="vWeight"></label><label class="full">Notes<textarea id="vNotes"></textarea></label></div><button class="primary" onclick="recordVitals()">Save Vitals</button><div id="vitalMessage"></div>`;
  $('staffPaymentsTab').innerHTML=`<h2>Record Payment</h2><div class="form-grid"><label class="full">Confirmed Patient<select id="payPatient">${opts||'<option value="">No patients registered</option>'}</select></label><label>Service<input id="payService"></label><label>Amount<input id="payAmount" type="number" min="0"></label><label>Method<select id="payMethod"><option>Cash</option><option>Transfer</option><option>Other</option></select></label><label>Status<select id="payStatus"><option>Paid</option><option>Pending</option></select></label><label>Reference<input id="payReference"></label></div><button class="primary" onclick="recordPayment()">Save Payment</button><div id="paymentMessage"></div>`;
  $('staffEmergenciesTab').innerHTML=`<h2>Emergency Requests</h2>${d.emergencies?.map(e=>`<div class="item"><h4>🚨 ${esc(e.name)}</h4>${esc(e.phone)}<br>${esc(e.condition)}<br><span class="badge">${esc(e.status)}</span></div>`).join('')||'<p class="identity">No emergency requests.</p>'}`;
}
function staffTab(name,btn){['staffPatientsTab','staffLookupTab','staffRegisterTab','staffVitalsTab','staffPaymentsTab','staffEmergenciesTab'].forEach(id=>$(id)?.classList.add('hidden'));const map={patients:'staffPatientsTab',lookup:'staffLookupTab',register:'staffRegisterTab',vitals:'staffVitalsTab',payments:'staffPaymentsTab',emergencies:'staffEmergenciesTab'};$(map[name])?.classList.remove('hidden');document.querySelectorAll('#staffDashboard .tabs button').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');}
async function staffRegister(){try{const d=await api('/api/staff/register-patient',{method:'POST',body:JSON.stringify({firstName:valueOf('sFirst'),lastName:valueOf('sLast'),cardType:valueOf('sCardType'),cardNumber:valueOf('sCardNumber'),cardName:valueOf('sCardName'),phone:valueOf('sPhone'),dob:valueOf('sDob'),sex:valueOf('sSex'),emergencyContact:valueOf('sEmergency'),createFamily:valueOf('sCardType')==='Family'})});openModal(`<h2>Patient Created</h2><p>${esc(d.message)}</p><div class="demo"><b>Patient:</b> ${esc(d.patient.firstName)} ${esc(d.patient.lastName)}<br><b>Card Type:</b> ${esc(d.patient.cardType)}<br><b>Card Number:</b> ${esc(d.patient.cardNumber)}<br><b>Card Name:</b> ${esc(d.patient.cardName)}</div><p class="identity">The patient signs in with Card Number + Card Type. No patient password is created.</p>`);await refreshStaff();}catch(e){notice('staffRegisterMessage',e.message);}}
async function lookupPatient(){try{const d=await api('/api/staff/lookup-card',{method:'POST',body:JSON.stringify({cardNumber:valueOf('lookupCardNumber'),cardType:valueOf('lookupCardType')})});$('lookupResults').innerHTML=`<div class="dashboard-card"><h3>${esc(d.cardType)} Card: ${esc(d.cardNumber)}</h3><p><b>Card Name:</b> ${esc(d.cardName)}</p>${d.patients.map(p=>`<div class="record"><b>${esc(p.firstName)} ${esc(p.lastName)}</b><br>${esc(p.phone||'')}<br><button class="primary" onclick="staffPatientDetails('${p.id}')">Enter Patient Page</button></div>`).join('')}</div>`;}catch(e){notice('lookupMessage',e.message);}}
async function staffPatientDetails(uid){try{const d=await api('/api/staff/patient/'+encodeURIComponent(uid));openModal(`<h2>Patient Page</h2>${recordHtml(d.patient)}<div class="form-grid"><button class="primary" onclick="preparePatientAction('${d.patient.id}','vitals')">Record Vitals</button><button class="primary" onclick="preparePatientAction('${d.patient.id}','payment')">Record Payment</button></div>`);}catch(e){alert(e.message);}}
function preparePatientAction(uid,type){closeModal();staffTab(type==='vitals'?'vitals':'payments',document.querySelector(`#staffDashboard .tabs button:nth-child(${type==='vitals'?4:5})`));const select=$(type==='vitals'?'vPatient':'payPatient');if(select)select.value=uid;}
function recordHtml(p){
  const appointments=(p.appointments||[]).map(a=>`<div class="item"><b>${esc(a.type)}</b> — ${esc(a.date)}<br><span class="badge">${esc(a.status)}</span><p>${esc(a.reason)}</p></div>`).join('')||'<p>None</p>';
  const prescriptions=(p.prescriptions||[]).map(r=>`<div class="item"><b>${esc(r.drugName)}</b> — ${esc(r.dosage)} — ${esc(r.frequency)} — ${esc(r.duration||'')}<br>${esc(r.instructions||'')}<br><span class="identity">${esc(r.doctorName||'Doctor')}</span></div>`).join('')||'<p>None</p>';
  const payments=(p.payments||[]).map(x=>`<div class="item">₦${esc(x.amount)} — ${esc(x.service)} — <span class="badge">${esc(x.method)}</span> ${esc(x.status)}<br><span class="identity">Recorded by ${esc(x.recordedByName||'Clinic')}</span></div>`).join('')||'<p>None</p>';
  const vitals=(p.vitals||[]).map(v=>`<div class="item">BP ${esc(v.bloodPressure)} • Pulse ${esc(v.pulse)} • Temp ${esc(v.temperature)}<br>SpO₂ ${esc(v.spo2||'')}<br>Recorded by ${esc(v.recordedByName)} — Staff ID <span class="badge">${esc(v.recordedByStaffId)}</span></div>`).join('')||'<p>None</p>';
  const family=(p.familyMembers||[]).map(m=>`<div class="item"><b>${esc(m.firstName)} ${esc(m.lastName)}</b> — ${esc(m.cardNumber||m.patientId||'')}<br>${esc(m.cardName||'')}</div>`).join('');
  return `<div class="record-page"><div class="record"><b>${esc(p.firstName)} ${esc(p.lastName)}</b><br><span class="badge">${esc(p.cardType)} Card</span> <span class="badge">${esc(p.cardNumber||p.patientId||'')}</span><br><b>Card Name:</b> ${esc(p.cardName||'')}<br><b>Family Card:</b> ${esc(p.familyCardNumber||'Not applicable')}<br><b>Phone:</b> ${esc(p.phone||'')}<br><b>DOB:</b> ${esc(p.dob||'')}<br><b>Sex:</b> ${esc(p.sex||'')}</div><h3>Appointments</h3>${appointments}<h3>Prescriptions</h3>${prescriptions}<h3>Payments</h3>${payments}<h3>Vitals</h3>${vitals}${family?`<h3>Family Card Members</h3>${family}`:''}</div>`;
}
async function recordVitals(){try{await api('/api/vitals',{method:'POST',body:JSON.stringify({patientUserId:valueOf('vPatient'),temperature:valueOf('vTemp'),bloodPressure:valueOf('vBP'),pulse:valueOf('vPulse'),respiratoryRate:valueOf('vResp'),spo2:valueOf('vSpo'),weight:valueOf('vWeight'),notes:valueOf('vNotes')})});notice('vitalMessage','Vitals recorded successfully.',true);}catch(e){notice('vitalMessage',e.message);}}
async function recordPayment(){try{await api('/api/payments',{method:'POST',body:JSON.stringify({patientUserId:valueOf('payPatient'),service:valueOf('payService'),amount:valueOf('payAmount'),method:valueOf('payMethod'),status:valueOf('payStatus'),reference:valueOf('payReference')})});notice('paymentMessage','Payment recorded successfully.',true);}catch(e){notice('paymentMessage',e.message);}}

async function loadDoctor(){const area=$('doctorDashboard');area.classList.remove('hidden');const d=await api('/api/doctor/dashboard');area.innerHTML=`<div class="dashboard-card"><div class="toolbar"><div><h2>Doctor Workspace</h2><p class="identity">Complete patient records are visible here. Staff controls remain separate.</p></div><span class="badge">Doctor ID: ${esc(me.doctorId)}</span></div></div><div class="dashboard-card" style="margin-top:18px"><h2>Patients</h2>${d.patients.map(p=>`<div class="record"><div class="toolbar"><div><h3 style="margin:0">${esc(p.firstName)} ${esc(p.lastName)}</h3><span class="badge">${esc(p.cardType)} Card</span> <span class="badge">${esc(p.cardNumber||p.patientId||'')}</span></div><button class="primary" onclick="doctorRecord('${p.id}')">Open Patient Record</button></div></div>`).join('')||'<p class="identity">No patients.</p>'}</div><div class="dashboard-card" style="margin-top:18px"><h2>Emergencies</h2>${d.emergencies.map(e=>`<div class="item"><h4>🚨 ${esc(e.name)}</h4>${esc(e.phone)}<br>${esc(e.condition)}<br><span class="badge">${esc(e.status)}</span></div>`).join('')||'<p class="identity">No emergency requests.</p>'}</div>`;}
async function doctorRecord(uid){try{const d=await api('/api/staff/patient/'+encodeURIComponent(uid));const p=d.patient;openModal(`<h2>${esc(p.firstName)} ${esc(p.lastName)}</h2>${recordHtml(p)}<h3>Doctor Actions</h3><div class="form-grid"><label>Drug Name<input id="rxDrug"></label><label>Dosage<input id="rxDose"></label><label>Frequency<input id="rxFreq"></label><label>Duration<input id="rxDuration"></label><label class="full">Instructions<textarea id="rxInstructions"></textarea></label></div><button class="primary" onclick="prescribe('${p.id}')">Save Prescription</button><div id="rxMessage"></div>`);}catch(e){alert(e.message);}}
async function prescribe(uid){try{await api('/api/prescriptions',{method:'POST',body:JSON.stringify({patientUserId:uid,drugName:valueOf('rxDrug'),dosage:valueOf('rxDose'),frequency:valueOf('rxFreq'),duration:valueOf('rxDuration'),instructions:valueOf('rxInstructions')})});notice('rxMessage','Prescription saved.',true);}catch(e){notice('rxMessage',e.message);}}

function adminShell(){return `<div class="tabs"><button class="active" onclick="adminTab('overview',this)">Overview</button><button onclick="adminTab('users',this)">Staff & Doctors</button><button onclick="adminTab('patients',this)">Patients</button><button onclick="adminTab('audit',this)">Audit Trail</button></div><div id="adminOverviewTab" class="dashboard-card"></div><div id="adminUsersTab" class="dashboard-card hidden"></div><div id="adminPatientsTab" class="dashboard-card hidden"></div><div id="adminAuditTab" class="dashboard-card hidden"></div>`;}
async function loadAdmin(){const area=$('adminDashboard');area.classList.remove('hidden');area.innerHTML=adminShell();await refreshAdmin();}
async function refreshAdmin(){const d=await api('/api/admin/dashboard');$('adminOverviewTab').innerHTML=`<h2>Administrator Dashboard</h2><div class="stats"><div class="stat"><strong>${d.users.filter(u=>u.role==='staff').length}/${d.limits.staff}</strong>Staff</div><div class="stat"><strong>${d.users.filter(u=>u.role==='doctor').length}/${d.limits.doctor}</strong>Doctors</div><div class="stat"><strong>${d.users.filter(u=>u.role==='admin').length}/${d.limits.admin}</strong>Administrators</div><div class="stat"><strong>${d.patients.length}</strong>Patients</div></div><p class="identity">Only the Administrator creates additional Staff and Doctor accounts.</p>`;$('adminUsersTab').innerHTML=`<h2>Staff & Doctor Accounts</h2><div id="adminUserMessage"></div><div class="form-grid"><label>Role<select id="aRole"><option>staff</option><option>doctor</option></select></label><label>Employee ID<input id="aEmployeeId"></label><label>First Name<input id="aFirst"></label><label>Last Name<input id="aLast"></label><label class="full">Email<input id="aEmail" type="email"></label></div><button class="primary" onclick="adminCreateUser()">Add Staff / Doctor</button><hr style="border:0;border-top:1px solid var(--line);margin:25px 0"><h3>Current Team</h3>${d.users.filter(u=>u.role==='staff'||u.role==='doctor').map(u=>`<div class="record"><b>${esc(u.firstName)} ${esc(u.lastName)}</b> — ${esc(u.role)} — ${esc(u.staffId||u.doctorId||'')} — ${esc(u.email||'')}</div>`).join('')}`;$('adminPatientsTab').innerHTML=`<h2>All Patient Records</h2>${d.patients.map(p=>`<div class="record"><div class="toolbar"><div><b>${esc(p.firstName)} ${esc(p.lastName)}</b><br><span class="badge">${esc(p.cardType)} Card</span> <span class="badge">${esc(p.cardNumber||p.patientId||'')}</span><br>${esc(p.cardName||'')}</div><button class="outline" onclick="adminPatient('${p.id}')">Open Record</button></div></div>`).join('')||'<p class="identity">No patients.</p>'}`;$('adminAuditTab').innerHTML=`<h2>Recent Audit Trail</h2>${d.audit.map(a=>`<div class="item"><b>${esc(a.action)}</b><br>${esc(a.target)}<br><span class="identity">${esc(a.at)}</span></div>`).join('')||'<p class="identity">No audit entries.</p>'}`;}
function adminTab(name,btn){['adminOverviewTab','adminUsersTab','adminPatientsTab','adminAuditTab'].forEach(id=>$(id)?.classList.add('hidden'));const map={overview:'adminOverviewTab',users:'adminUsersTab',patients:'adminPatientsTab',audit:'adminAuditTab'};$(map[name])?.classList.remove('hidden');document.querySelectorAll('#adminDashboard .tabs button').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');}
async function adminCreateUser(){try{const d=await api('/api/admin/create-user',{method:'POST',body:JSON.stringify({role:valueOf('aRole'),employeeId:valueOf('aEmployeeId'),firstName:valueOf('aFirst'),lastName:valueOf('aLast'),email:valueOf('aEmail')})});openModal(`<h2>${esc(d.user.role)} account created</h2><div class="demo"><b>Name:</b> ${esc(d.user.firstName)} ${esc(d.user.lastName)}<br><b>ID:</b> ${esc(d.user.staffId||d.user.doctorId)}<br><b>Email:</b> ${esc(d.user.email)}<br><b>Temporary Password:</b> ${esc(d.temporaryPassword)}</div>`);await refreshAdmin();}catch(e){notice('adminUserMessage',e.message);}}
async function adminPatient(uid){try{const d=await api('/api/staff/patient/'+encodeURIComponent(uid));openModal(`<h2>Patient Record</h2>${recordHtml(d.patient)}`);}catch(e){alert(e.message);}}
function openPasswordChange(force){openModal(`<h2>${force?'Change Your Temporary Password':'Change Password'}</h2><p class="identity">Use at least 8 characters.</p><div id="changePassMessage"></div><label>Current Password<input id="currentPass" type="password"></label><label>New Password<input id="newPass" type="password"></label><button class="primary" onclick="changePassword()">Save Password</button>`);}
async function changePassword(){try{await api('/api/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:valueOf('currentPass'),newPassword:valueOf('newPass')})});notice('changePassMessage','Password changed successfully.',true);setTimeout(closeModal,600);}catch(e){notice('changePassMessage',e.message);}}
async function sendEmergency(){try{const d=await api('/api/emergency',{method:'POST',body:JSON.stringify({name:valueOf('emName'),phone:valueOf('emPhone'),condition:valueOf('emCondition')})});notice('emergencyMessage',d.message,true);}catch(e){notice('emergencyMessage',e.message);}}
async function logout(){try{await api('/api/auth/logout',{method:'POST'});}catch{}me=null;$('logoutBtn')?.classList.add('hidden');goHome();}

document.addEventListener('DOMContentLoaded',()=>{updateLoginFields();});
(async()=>{try{const d=await api('/api/me');if(d.user){me=d.user;await loadDashboard();}}catch{}})();
